mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                provider: 'App\Mercure\MyTokenProvider'
    enable_profiler: '%kernel.debug%'